use_frameworks!

target 'WATableViewAdapter_Example' do
  pod 'WATableViewAdapter', :path => '../'
  pod 'SwipeCellKit'

  target 'WATableViewAdapter_Tests' do
    inherit! :search_paths

    
  end
end
